### ISSUE TITLE
Hi, is it necessary to give a pretrained weights for the generator?

### ISSUE THREAD

**Issue by ChuChenLi** [MrRobot2211/pytorch-deep-photo-enhancer#2]
Thank you for your code. It is very clear and helpful!  I'm trying to implement this work on my own data. I'm a little bit confused about is it necessary to pre-train weights for the generator? The instructions in README.md let me think I need to do SL before doing UL. But it isn't mentioned in the paper. Is a pretrained generator necessary?

Thank you!

**Comment by MrRobot2211** [comment]
You need to rrun the _v3 version. No pretraining required at all.

**Comment by MrRobot2211** [comment]
Iam adding a reademe today so that it is clear for everyone

**Comment by MrRobot2211** [comment]
I added the readme if you want to check, tell me if there is something missing
